### ISSUE TITLE
Support PRINTK_CALLER kernel compilation option

### ISSUE THREAD

**Issue by happy-dude** [talos-systems/go-kmsg#10]
Hey team,

Thanks for such a wonderful module. 

I was wondering if it's would be possible to support the PRINTK_CALLER[1] kernel option, which adds an additional field in the kmsg record header noting the tread or cpuid that emitted the message?

I may be able to contribute a patch/PR myself once I hear some thoughts regarding how is should be represented in the struct. I was thinking another struct to hold the numeric ID and a string to hold denote if it's a threadid or cpuid? 

Thanks a ton; looking forward to hearing back!

Stan

[1] https://cateee.net/lkddb/web-lkddb/PRINTK_CALLER.html

**Comment by happy-dude** [comment]
Here is a sample of (raw) kmsg log lines from a VirtualBox Ubuntu instance:

```
6,378,3059320,-,caller=T148;ata1: SATA max UDMA/133 abar m8192@0xf0820000 port 0xf0820100 irq 21
6,379,3282668,-,caller=T109;input: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input4
6,380,3492677,-,caller=T166;ata1: SATA link up 3.0 Gbps (SStatus 123 SControl 300)
6,381,3492831,-,caller=T166;ata1.00: ATA-6: VBOX HARDDISK, 1.0, max UDMA/133
6,382,3492836,-,caller=T166;ata1.00: 83886080 sectors, multi 128: LBA48 NCQ (depth 32)
6,383,3493296,-,caller=T166;ata1.00: configured for UDMA/133
5,384,3493489,-,caller=T10;scsi 0:0:0:0: Direct-Access     ATA      VBOX HARDDISK    1.0  PQ: 0 ANSI: 5
```

Having PRINTK_CALLER enabled makes it easier to correlate kernel messages from the same thread / CPU and quickly identify related issues.

**Comment by smira** [comment]
I guess it can be added to the `Message` struct as an additional field. This library at the moment only parses only first three parts in the metadata section.

**Comment by happy-dude** [comment]
I'll look into adding a patch! I'll have a struct with 2 fields, ID and an enum for type (thread or cpu). Will look for feedback there.
