### ISSUE TITLE
Exit when the context is closed

### ISSUE THREAD

**Issue by dud225** [talos-systems/go-kmsg#4]
Hello

in the current code the execution continues even if the provided context is closed:
```
	for {
		[....]

		select {
		case ch <- packet:
		case <-ctx.Done():
		}
	}
```

shouldn't the for loop be ended whenever the ctx context is closed?

**Comment by smira** [comment]
yes, this looks like a bug, and actually the code can be improved in many places

**Comment by dud225** [comment]
OK I've drafted a PR for that specific issue: https://github.com/siderolabs/go-kmsg/pull/5
